export interface Country {
  id: number;
  name: string;
  flag: string;
  region: string;
  subregion: string;
  capital: string;
  languages: string[];
  currency: {
    name: string;
    symbol: string;
  };
}

export const countries: Country[] = [
  {
    id: 1,
    name: "India",
    flag: "https://flagcdn.com/w320/in.png",
    region: "Asia",
    subregion: "Southern Asia",
    capital: "New Delhi",
    languages: ["Hindi", "English"],
    currency: {
      name: "Indian Rupee",
      symbol: "₹",
    },
  },
  {
    id: 2,
    name: "Pakistan",
    flag: "https://flagcdn.com/w320/pk.png",
    region: "Asia",
    subregion: "Southern Asia",
    capital: "Islamabad",
    languages: ["Urdu", "English"],
    currency: {
      name: "Pakistani Rupee",
      symbol: "₨",
    },
  },
  {
    id: 3,
    name: "Bangladesh",
    flag: "https://flagcdn.com/w320/bd.png",
    region: "Asia",
    subregion: "Southern Asia",
    capital: "Dhaka",
    languages: ["Bengali"],
    currency: {
      name: "Taka",
      symbol: "৳",
    },
  },
  
  {
  id: 4,
  name: "Gabon",
  flag: "https://flagcdn.com/w160/ga.png",
  region: "Africa",
  subregion: "Middle Africa",
  capital: "Libreville",
  languages: ["French"],
  currency: {
    name: "Central African CFA Franc",
    symbol: "FCFA",
  },
},
  {
    id: 5,
    name: "Sri Lanka",
    flag: "https://flagcdn.com/w320/lk.png",
    region: "Asia",
    subregion: "Southern Asia",
    capital: "Sri Jayawardenepura Kotte",
    languages: ["Sinhala", "Tamil"],
    currency: {
      name: "Sri Lankan Rupee",
      symbol: "Rs",
    },
  },
  {
    id: 6,
    name: "Bhutan",
    flag: "https://flagcdn.com/w320/bt.png",
    region: "Asia",
    subregion: "Southern Asia",
    capital: "Thimphu",
    languages: ["Dzongkha"],
    currency: {
      name: "Ngultrum",
      symbol: "Nu.",
    },
  },
  {
    id: 7,
    name: "China",
    flag: "https://flagcdn.com/w320/cn.png",
    region: "Asia",
    subregion: "Eastern Asia",
    capital: "Beijing",
    languages: ["Mandarin Chinese"],
    currency: {
      name: "Renminbi",
      symbol: "¥",
    },
  },
  {
    id: 8,
    name: "Japan",
    flag: "https://flagcdn.com/w320/jp.png",
    region: "Asia",
    subregion: "Eastern Asia",
    capital: "Tokyo",
    languages: ["Japanese"],
    currency: {
      name: "Japanese Yen",
      symbol: "¥",
    },
  },
  {
    id: 9,
    name: "Germany",
    flag: "https://flagcdn.com/w320/de.png",
    region: "Europe",
    subregion: "Western Europe",
    capital: "Berlin",
    languages: ["German"],
    currency: {
      name: "Euro",
      symbol: "€",
    },
  },
  {
    id: 10,
    name: "France",
    flag: "https://flagcdn.com/w320/fr.png",
    region: "Europe",
    subregion: "Western Europe",
    capital: "Paris",
    languages: ["French"],
    currency: {
      name: "Euro",
      symbol: "€",
    },
  },
  {
  id: 11,
  name: "Italy",
  flag: "https://flagcdn.com/w160/it.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "Rome",
  languages: ["Italian"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 12,
  name: "Spain",
  flag: "https://flagcdn.com/w160/es.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "Madrid",
  languages: ["Spanish"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 13,
  name: "United Kingdom",
  flag: "https://flagcdn.com/w160/gb.png",
  region: "Europe",
  subregion: "Northern Europe",
  capital: "London",
  languages: ["English"],
  currency: {
    name: "Pound Sterling",
    symbol: "£",
  },
},
{
  id: 14,
  name: "United States",
  flag: "https://flagcdn.com/w160/us.png",
  region: "North America",
  subregion: "Northern America",
  capital: "Washington, D.C.",
  languages: ["English"],
  currency: {
    name: "United States Dollar",
    symbol: "$",
  },
},
{
  id: 15,
  name: "Canada",
  flag: "https://flagcdn.com/w160/ca.png",
  region: "North America",
  subregion: "Northern America",
  capital: "Ottawa",
  languages: ["English", "French"],
  currency: {
    name: "Canadian Dollar",
    symbol: "$",
  },
},
{
  id: 16,
  name: "Mexico",
  flag: "https://flagcdn.com/w160/mx.png",
  region: "North America",
  subregion: "Central America",
  capital: "Mexico City",
  languages: ["Spanish"],
  currency: {
    name: "Mexican Peso",
    symbol: "$",
  },
},
{
  id: 17,
  name: "Brazil",
  flag: "https://flagcdn.com/w160/br.png",
  region: "South America",
  subregion: "South America",
  capital: "Brasília",
  languages: ["Portuguese"],
  currency: {
    name: "Brazilian Real",
    symbol: "R$",
  },
},
{
  id: 18,
  name: "Argentina",
  flag: "https://flagcdn.com/w160/ar.png",
  region: "South America",
  subregion: "South America",
  capital: "Buenos Aires",
  languages: ["Spanish"],
  currency: {
    name: "Argentine Peso",
    symbol: "$",
  },
},
{
  id: 19,
  name: "Australia",
  flag: "https://flagcdn.com/w160/au.png",
  region: "Oceania",
  subregion: "Australia and New Zealand",
  capital: "Canberra",
  languages: ["English"],
  currency: {
    name: "Australian Dollar",
    symbol: "$",
  },
},
{
  id: 20,
  name: "New Zealand",
  flag: "https://flagcdn.com/w160/nz.png",
  region: "Oceania",
  subregion: "Australia and New Zealand",
  capital: "Wellington",
  languages: ["English", "Māori", "New Zealand Sign Language"],
  currency: {
    name: "New Zealand Dollar",
    symbol: "$",
  },
},
{
  id: 21,
  name: "South Korea",
  flag: "https://flagcdn.com/w160/kr.png",
  region: "Asia",
  subregion: "Eastern Asia",
  capital: "Seoul",
  languages: ["Korean"],
  currency: {
    name: "South Korean Won",
    symbol: "₩",
  },
},
{
  id: 22,
  name: "North Korea",
  flag: "https://flagcdn.com/w160/kp.png",
  region: "Asia",
  subregion: "Eastern Asia",
  capital: "Pyongyang",
  languages: ["Korean"],
  currency: {
    name: "North Korean Won",
    symbol: "₩",
  },
},
{
  id: 23,
  name: "Mongolia",
  flag: "https://flagcdn.com/w160/mn.png",
  region: "Asia",
  subregion: "Eastern Asia",
  capital: "Ulaanbaatar",
  languages: ["Mongolian"],
  currency: {
    name: "Tögrög",
    symbol: "₮",
  },
},
{
  id: 24,
  name: "Thailand",
  flag: "https://flagcdn.com/w160/th.png",
  region: "Asia",
  subregion: "South-Eastern Asia",
  capital: "Bangkok",
  languages: ["Thai"],
  currency: {
    name: "Baht",
    symbol: "฿",
  },
},
{
  id: 25,
  name: "Vietnam",
  flag: "https://flagcdn.com/w160/vn.png",
  region: "Asia",
  subregion: "South-Eastern Asia",
  capital: "Hanoi",
  languages: ["Vietnamese"],
  currency: {
    name: "Vietnamese Đồng",
    symbol: "₫",
  },
},
{
  id: 26,
  name: "Malaysia",
  flag: "https://flagcdn.com/w160/my.png",
  region: "Asia",
  subregion: "South-Eastern Asia",
  capital: "Kuala Lumpur",
  languages: ["Malay"],
  currency: {
    name: "Malaysian Ringgit",
    symbol: "RM",
  },
},
{
  id: 27,
  name: "Singapore",
  flag: "https://flagcdn.com/w160/sg.png",
  region: "Asia",
  subregion: "South-Eastern Asia",
  capital: "Singapore",
  languages: ["English", "Malay", "Mandarin", "Tamil"],
  currency: {
    name: "Singapore Dollar",
    symbol: "$",
  },
},
{
  id: 28,
  name: "Indonesia",
  flag: "https://flagcdn.com/w160/id.png",
  region: "Asia",
  subregion: "South-Eastern Asia",
  capital: "Jakarta",
  languages: ["Indonesian"],
  currency: {
    name: "Indonesian Rupiah",
    symbol: "Rp",
  },
},
{
  id: 29,
  name: "Philippines",
  flag: "https://flagcdn.com/w160/ph.png",
  region: "Asia",
  subregion: "South-Eastern Asia",
  capital: "Manila",
  languages: ["Filipino", "English"],
  currency: {
    name: "Philippine Peso",
    symbol: "₱",
  },
},
{
  id: 30,
  name: "Myanmar",
  flag: "https://flagcdn.com/w160/mm.png",
  region: "Asia",
  subregion: "South-Eastern Asia",
  capital: "Naypyidaw",
  languages: ["Burmese"],
  currency: {
    name: "Kyat",
    symbol: "Ks",
  },
},
{
  id: 31,
  name: "Cambodia",
  flag: "https://flagcdn.com/w160/kh.png",
  region: "Asia",
  subregion: "South-Eastern Asia",
  capital: "Phnom Penh",
  languages: ["Khmer"],
  currency: {
    name: "Riel",
    symbol: "៛",
  },
},
{
  id: 32,
  name: "Laos",
  flag: "https://flagcdn.com/w160/la.png",
  region: "Asia",
  subregion: "South-Eastern Asia",
  capital: "Vientiane",
  languages: ["Lao"],
  currency: {
    name: "Lao Kip",
    symbol: "₭",
  },
},
{
  id: 33,
  name: "Brunei",
  flag: "https://flagcdn.com/w160/bn.png",
  region: "Asia",
  subregion: "South-Eastern Asia",
  capital: "Bandar Seri Begawan",
  languages: ["Malay"],
  currency: {
    name: "Brunei Dollar",
    symbol: "$",
  },
},
{
  id: 34,
  name: "Timor-Leste",
  flag: "https://flagcdn.com/w160/tl.png",
  region: "Asia",
  subregion: "South-Eastern Asia",
  capital: "Dili",
  languages: ["Tetum", "Portuguese"],
  currency: {
    name: "United States Dollar",
    symbol: "$",
  },
},
{
  id: 35,
  name: "Russia",
  flag: "https://flagcdn.com/w160/ru.png",
  region: "Europe",
  subregion: "Eastern Europe",
  capital: "Moscow",
  languages: ["Russian"],
  currency: {
    name: "Russian Ruble",
    symbol: "₽",
  },
},
{
  id: 36,
  name: "Ukraine",
  flag: "https://flagcdn.com/w160/ua.png",
  region: "Europe",
  subregion: "Eastern Europe",
  capital: "Kyiv",
  languages: ["Ukrainian"],
  currency: {
    name: "Hryvnia",
    symbol: "₴",
  },
},
{
  id: 37,
  name: "Poland",
  flag: "https://flagcdn.com/w160/pl.png",
  region: "Europe",
  subregion: "Central Europe",
  capital: "Warsaw",
  languages: ["Polish"],
  currency: {
    name: "Polish Złoty",
    symbol: "zł",
  },
},
{
  id: 38,
  name: "Netherlands",
  flag: "https://flagcdn.com/w160/nl.png",
  region: "Europe",
  subregion: "Western Europe",
  capital: "Amsterdam",
  languages: ["Dutch"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 39,
  name: "Belgium",
  flag: "https://flagcdn.com/w160/be.png",
  region: "Europe",
  subregion: "Western Europe",
  capital: "Brussels",
  languages: ["Dutch", "French", "German"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 40,
  name: "Switzerland",
  flag: "https://flagcdn.com/w160/ch.png",
  region: "Europe",
  subregion: "Western Europe",
  capital: "Bern",
  languages: ["German", "French", "Italian", "Romansh"],
  currency: {
    name: "Swiss Franc",
    symbol: "CHF",
  },
},
{
  id: 41,
  name: "Austria",
  flag: "https://flagcdn.com/w160/at.png",
  region: "Europe",
  subregion: "Central Europe",
  capital: "Vienna",
  languages: ["German"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 42,
  name: "Czech Republic",
  flag: "https://flagcdn.com/w160/cz.png",
  region: "Europe",
  subregion: "Central Europe",
  capital: "Prague",
  languages: ["Czech"],
  currency: {
    name: "Czech Koruna",
    symbol: "Kč",
  },
},
{
  id: 43,
  name: "Slovakia",
  flag: "https://flagcdn.com/w160/sk.png",
  region: "Europe",
  subregion: "Central Europe",
  capital: "Bratislava",
  languages: ["Slovak"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 44,
  name: "Hungary",
  flag: "https://flagcdn.com/w160/hu.png",
  region: "Europe",
  subregion: "Central Europe",
  capital: "Budapest",
  languages: ["Hungarian"],
  currency: {
    name: "Forint",
    symbol: "Ft",
  },
},
{
  id: 45,
  name: "Romania",
  flag: "https://flagcdn.com/w160/ro.png",
  region: "Europe",
  subregion: "Eastern Europe",
  capital: "Bucharest",
  languages: ["Romanian"],
  currency: {
    name: "Romanian Leu",
    symbol: "lei",
  },
},
{
  id: 46,
  name: "Bulgaria",
  flag: "https://flagcdn.com/w160/bg.png",
  region: "Europe",
  subregion: "Eastern Europe",
  capital: "Sofia",
  languages: ["Bulgarian"],
  currency: {
    name: "Bulgarian Lev",
    symbol: "лв",
  },
},
{
  id: 47,
  name: "Greece",
  flag: "https://flagcdn.com/w160/gr.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "Athens",
  languages: ["Greek"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 48,
  name: "Portugal",
  flag: "https://flagcdn.com/w160/pt.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "Lisbon",
  languages: ["Portuguese"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 49,
  name: "Ireland",
  flag: "https://flagcdn.com/w160/ie.png",
  region: "Europe",
  subregion: "Northern Europe",
  capital: "Dublin",
  languages: ["Irish", "English"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 50,
  name: "Denmark",
  flag: "https://flagcdn.com/w160/dk.png",
  region: "Europe",
  subregion: "Northern Europe",
  capital: "Copenhagen",
  languages: ["Danish"],
  currency: {
    name: "Danish Krone",
    symbol: "kr",
  },
},
{
  id: 51,
  name: "Norway",
  flag: "https://flagcdn.com/w160/no.png",
  region: "Europe",
  subregion: "Northern Europe",
  capital: "Oslo",
  languages: ["Norwegian"],
  currency: {
    name: "Norwegian Krone",
    symbol: "kr",
  },
},
{
  id: 52,
  name: "Sweden",
  flag: "https://flagcdn.com/w160/se.png",
  region: "Europe",
  subregion: "Northern Europe",
  capital: "Stockholm",
  languages: ["Swedish"],
  currency: {
    name: "Swedish Krona",
    symbol: "kr",
  },
},
{
  id: 53,
  name: "Finland",
  flag: "https://flagcdn.com/w160/fi.png",
  region: "Europe",
  subregion: "Northern Europe",
  capital: "Helsinki",
  languages: ["Finnish", "Swedish"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 54,
  name: "Iceland",
  flag: "https://flagcdn.com/w160/is.png",
  region: "Europe",
  subregion: "Northern Europe",
  capital: "Reykjavík",
  languages: ["Icelandic"],
  currency: {
    name: "Icelandic Króna",
    symbol: "kr",
  },
},
{
  id: 55,
  name: "Croatia",
  flag: "https://flagcdn.com/w160/hr.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "Zagreb",
  languages: ["Croatian"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 56,
  name: "Serbia",
  flag: "https://flagcdn.com/w160/rs.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "Belgrade",
  languages: ["Serbian"],
  currency: {
    name: "Serbian Dinar",
    symbol: "дин",
  },
},
{
  id: 57,
  name: "Slovenia",
  flag: "https://flagcdn.com/w160/si.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "Ljubljana",
  languages: ["Slovene"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 58,
  name: "Bosnia and Herzegovina",
  flag: "https://flagcdn.com/w160/ba.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "Sarajevo",
  languages: ["Bosnian", "Croatian", "Serbian"],
  currency: {
    name: "Convertible Mark",
    symbol: "KM",
  },
},
{
  id: 59,
  name: "Montenegro",
  flag: "https://flagcdn.com/w160/me.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "Podgorica",
  languages: ["Montenegrin"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 60,
  name: "Albania",
  flag: "https://flagcdn.com/w160/al.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "Tirana",
  languages: ["Albanian"],
  currency: {
    name: "Albanian Lek",
    symbol: "L",
  },
},
{
  id: 61,
  name: "Turkey",
  flag: "https://flagcdn.com/w160/tr.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Ankara",
  languages: ["Turkish"],
  currency: {
    name: "Turkish Lira",
    symbol: "₺",
  },
},
{
  id: 62,
  name: "Saudi Arabia",
  flag: "https://flagcdn.com/w160/sa.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Riyadh",
  languages: ["Arabic"],
  currency: {
    name: "Saudi Riyal",
    symbol: "﷼",
  },
},
{
  id: 63,
  name: "United Arab Emirates",
  flag: "https://flagcdn.com/w160/ae.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Abu Dhabi",
  languages: ["Arabic"],
  currency: {
    name: "UAE Dirham",
    symbol: "د.إ",
  },
},
{
  id: 64,
  name: "Qatar",
  flag: "https://flagcdn.com/w160/qa.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Doha",
  languages: ["Arabic"],
  currency: {
    name: "Qatari Riyal",
    symbol: "﷼",
  },
},
{
  id: 65,
  name: "Kuwait",
  flag: "https://flagcdn.com/w160/kw.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Kuwait City",
  languages: ["Arabic"],
  currency: {
    name: "Kuwaiti Dinar",
    symbol: "د.ك",
  },
},
{
  id: 66,
  name: "Bahrain",
  flag: "https://flagcdn.com/w160/bh.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Manama",
  languages: ["Arabic"],
  currency: {
    name: "Bahraini Dinar",
    symbol: ".د.ب",
  },
},
{
  id: 67,
  name: "Oman",
  flag: "https://flagcdn.com/w160/om.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Muscat",
  languages: ["Arabic"],
  currency: {
    name: "Omani Rial",
    symbol: "﷼",
  },
},
{
  id: 68,
  name: "Yemen",
  flag: "https://flagcdn.com/w160/ye.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Sana'a",
  languages: ["Arabic"],
  currency: {
    name: "Yemeni Rial",
    symbol: "﷼",
  },
},
{
  id: 69,
  name: "Iran",
  flag: "https://flagcdn.com/w160/ir.png",
  region: "Asia",
  subregion: "Southern Asia",
  capital: "Tehran",
  languages: ["Persian"],
  currency: {
    name: "Iranian Rial",
    symbol: "﷼",
  },
},
{
  id: 70,
  name: "Iraq",
  flag: "https://flagcdn.com/w160/iq.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Baghdad",
  languages: ["Arabic", "Kurdish"],
  currency: {
    name: "Iraqi Dinar",
    symbol: "ع.د",
  },
},
{
  id: 71,
  name: "Israel",
  flag: "https://flagcdn.com/w160/il.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Jerusalem",
  languages: ["Hebrew"],
  currency: {
    name: "Israeli New Shekel",
    symbol: "₪",
  },
},
{
  id: 72,
  name: "Jordan",
  flag: "https://flagcdn.com/w160/jo.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Amman",
  languages: ["Arabic"],
  currency: {
    name: "Jordanian Dinar",
    symbol: "د.ا",
  },
},
{
  id: 73,
  name: "Lebanon",
  flag: "https://flagcdn.com/w160/lb.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Beirut",
  languages: ["Arabic"],
  currency: {
    name: "Lebanese Pound",
    symbol: "ل.ل",
  },
},
{
  id: 74,
  name: "Syria",
  flag: "https://flagcdn.com/w160/sy.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Damascus",
  languages: ["Arabic"],
  currency: {
    name: "Syrian Pound",
    symbol: "£",
  },
},
{
  id: 75,
  name: "Vatican City",
  flag: "https://flagcdn.com/w160/va.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "Vatican City",
  languages: ["Italian", "Latin"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 76,
  name: "Kazakhstan",
  flag: "https://flagcdn.com/w160/kz.png",
  region: "Asia",
  subregion: "Central Asia",
  capital: "Astana",
  languages: ["Kazakh", "Russian"],
  currency: {
    name: "Tenge",
    symbol: "₸",
  },
},
{
  id: 77,
  name: "Uzbekistan",
  flag: "https://flagcdn.com/w160/uz.png",
  region: "Asia",
  subregion: "Central Asia",
  capital: "Tashkent",
  languages: ["Uzbek"],
  currency: {
    name: "Uzbekistani So'm",
    symbol: "so'm",
  },
},
{
  id: 78,
  name: "Turkmenistan",
  flag: "https://flagcdn.com/w160/tm.png",
  region: "Asia",
  subregion: "Central Asia",
  capital: "Ashgabat",
  languages: ["Turkmen"],
  currency: {
    name: "Turkmenistan Manat",
    symbol: "m",
  },
},
{
  id: 79,
  name: "Kyrgyzstan",
  flag: "https://flagcdn.com/w160/kg.png",
  region: "Asia",
  subregion: "Central Asia",
  capital: "Bishkek",
  languages: ["Kyrgyz", "Russian"],
  currency: {
    name: "Som",
    symbol: "с",
  },
},
{
  id: 80,
  name: "Tajikistan",
  flag: "https://flagcdn.com/w160/tj.png",
  region: "Asia",
  subregion: "Central Asia",
  capital: "Dushanbe",
  languages: ["Tajik"],
  currency: {
    name: "Somoni",
    symbol: "ЅМ",
  },
},
{
  id: 81,
  name: "Azerbaijan",
  flag: "https://flagcdn.com/w160/az.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Baku",
  languages: ["Azerbaijani"],
  currency: {
    name: "Azerbaijani Manat",
    symbol: "₼",
  },
},
{
  id: 82,
  name: "Armenia",
  flag: "https://flagcdn.com/w160/am.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Yerevan",
  languages: ["Armenian"],
  currency: {
    name: "Armenian Dram",
    symbol: "֏",
  },
},
{
  id: 83,
  name: "Georgia",
  flag: "https://flagcdn.com/w160/ge.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Tbilisi",
  languages: ["Georgian"],
  currency: {
    name: "Georgian Lari",
    symbol: "₾",
  },
},
{
  id: 84,
  name: "Maldives",
  flag: "https://flagcdn.com/w160/mv.png",
  region: "Asia",
  subregion: "Southern Asia",
  capital: "Malé",
  languages: ["Dhivehi"],
  currency: {
    name: "Maldivian Rufiyaa",
    symbol: "Rf",
  },
},
{
  id: 85,
  name: "Mauritius",
  flag: "https://flagcdn.com/w160/mu.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Port Louis",
  languages: ["English", "French"],
  currency: {
    name: "Mauritian Rupee",
    symbol: "₨",
  },
},
{
  id: 86,
  name: "Seychelles",
  flag: "https://flagcdn.com/w160/sc.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Victoria",
  languages: ["Seychellois Creole", "English", "French"],
  currency: {
    name: "Seychellois Rupee",
    symbol: "₨",
  },
},
{
  id: 87,
  name: "Madagascar",
  flag: "https://flagcdn.com/w160/mg.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Antananarivo",
  languages: ["Malagasy", "French"],
  currency: {
    name: "Malagasy Ariary",
    symbol: "Ar",
  },
},
{
  id: 88,
  name: "South Africa",
  flag: "https://flagcdn.com/w160/za.png",
  region: "Africa",
  subregion: "Southern Africa",
  capital: "Pretoria",
  languages: [
    "Zulu",
    "Xhosa",
    "Afrikaans",
    "English"
  ],
  currency: {
    name: "South African Rand",
    symbol: "R",
  },
},
{
  id: 89,
  name: "Namibia",
  flag: "https://flagcdn.com/w160/na.png",
  region: "Africa",
  subregion: "Southern Africa",
  capital: "Windhoek",
  languages: ["English"],
  currency: {
    name: "Namibian Dollar",
    symbol: "$",
  },
},
{
  id: 90,
  name: "Botswana",
  flag: "https://flagcdn.com/w160/bw.png",
  region: "Africa",
  subregion: "Southern Africa",
  capital: "Gaborone",
  languages: ["English", "Tswana"],
  currency: {
    name: "Botswana Pula",
    symbol: "P",
  },
},
{
  id: 91,
  name: "Zimbabwe",
  flag: "https://flagcdn.com/w160/zw.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Harare",
  languages: ["English", "Shona", "Ndebele"],
  currency: {
    name: "Zimbabwe Gold",
    symbol: "ZiG",
  },
},
{
  id: 92,
  name: "Zambia",
  flag: "https://flagcdn.com/w160/zm.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Lusaka",
  languages: ["English"],
  currency: {
    name: "Zambian Kwacha",
    symbol: "ZK",
  },
},
{
  id: 93,
  name: "Mozambique",
  flag: "https://flagcdn.com/w160/mz.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Maputo",
  languages: ["Portuguese"],
  currency: {
    name: "Mozambican Metical",
    symbol: "MT",
  },
},
{
  id: 94,
  name: "Angola",
  flag: "https://flagcdn.com/w160/ao.png",
  region: "Africa",
  subregion: "Middle Africa",
  capital: "Luanda",
  languages: ["Portuguese"],
  currency: {
    name: "Kwanza",
    symbol: "Kz",
  },
},
{
  id: 95,
  name: "Democratic Republic of the Congo",
  flag: "https://flagcdn.com/w160/cd.png",
  region: "Africa",
  subregion: "Middle Africa",
  capital: "Kinshasa",
  languages: ["French"],
  currency: {
    name: "Congolese Franc",
    symbol: "FC",
  },
},
{
  id: 96,
  name: "Republic of the Congo",
  flag: "https://flagcdn.com/w160/cg.png",
  region: "Africa",
  subregion: "Middle Africa",
  capital: "Brazzaville",
  languages: ["French"],
  currency: {
    name: "Central African CFA Franc",
    symbol: "FCFA",
  },
},
{
  id: 97,
  name: "Cameroon",
  flag: "https://flagcdn.com/w160/cm.png",
  region: "Africa",
  subregion: "Middle Africa",
  capital: "Yaoundé",
  languages: ["English", "French"],
  currency: {
    name: "Central African CFA Franc",
    symbol: "FCFA",
  },
},
{
  id: 98,
  name: "Central African Republic",
  flag: "https://flagcdn.com/w160/cf.png",
  region: "Africa",
  subregion: "Middle Africa",
  capital: "Bangui",
  languages: ["French", "Sango"],
  currency: {
    name: "Central African CFA Franc",
    symbol: "FCFA",
  },
},
{
  id: 99,
  name: "Chad",
  flag: "https://flagcdn.com/w160/td.png",
  region: "Africa",
  subregion: "Middle Africa",
  capital: "N'Djamena",
  languages: ["French", "Arabic"],
  currency: {
    name: "Central African CFA Franc",
    symbol: "FCFA",
  },
},
{
    id: 100,
    name: "Nepal",
    flag: "https://flagcdn.com/w320/np.png",
    region: "Asia",
    subregion: "Southern Asia",
    capital: "Kathmandu",
    languages: ["Nepali"],
    currency: {
      name: "Nepalese Rupee",
      symbol: "₨",
    },
  },
{
  id: 101,
  name: "Nigeria",
  flag: "https://flagcdn.com/w160/ng.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Abuja",
  languages: ["English"],
  currency: {
    name: "Naira",
    symbol: "₦",
  },
},
{
  id: 102,
  name: "Ghana",
  flag: "https://flagcdn.com/w160/gh.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Accra",
  languages: ["English"],
  currency: {
    name: "Ghanaian Cedi",
    symbol: "₵",
  },
},
{
  id: 103,
  name: "Ivory Coast",
  flag: "https://flagcdn.com/w160/ci.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Yamoussoukro",
  languages: ["French"],
  currency: {
    name: "West African CFA Franc",
    symbol: "CFA",
  },
},
{
  id: 104,
  name: "Senegal",
  flag: "https://flagcdn.com/w160/sn.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Dakar",
  languages: ["French"],
  currency: {
    name: "West African CFA Franc",
    symbol: "CFA",
  },
},
{
  id: 105,
  name: "Mali",
  flag: "https://flagcdn.com/w160/ml.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Bamako",
  languages: ["French"],
  currency: {
    name: "West African CFA Franc",
    symbol: "CFA",
  },
},
{
  id: 106,
  name: "Burkina Faso",
  flag: "https://flagcdn.com/w160/bf.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Ouagadougou",
  languages: ["French"],
  currency: {
    name: "West African CFA Franc",
    symbol: "CFA",
  },
},
{
  id: 107,
  name: "Niger",
  flag: "https://flagcdn.com/w160/ne.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Niamey",
  languages: ["French"],
  currency: {
    name: "West African CFA Franc",
    symbol: "CFA",
  },
},
{
  id: 108,
  name: "Benin",
  flag: "https://flagcdn.com/w160/bj.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Porto-Novo",
  languages: ["French"],
  currency: {
    name: "West African CFA Franc",
    symbol: "CFA",
  },
},
{
  id: 109,
  name: "Togo",
  flag: "https://flagcdn.com/w160/tg.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Lomé",
  languages: ["French"],
  currency: {
    name: "West African CFA Franc",
    symbol: "CFA",
  },
},
{
  id: 110,
  name: "Guinea",
  flag: "https://flagcdn.com/w160/gn.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Conakry",
  languages: ["French"],
  currency: {
    name: "Guinean Franc",
    symbol: "FG",
  },
},
{
  id: 111,
  name: "Sierra Leone",
  flag: "https://flagcdn.com/w160/sl.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Freetown",
  languages: ["English"],
  currency: {
    name: "Leone",
    symbol: "Le",
  },
},
{
  id: 112,
  name: "Liberia",
  flag: "https://flagcdn.com/w160/lr.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Monrovia",
  languages: ["English"],
  currency: {
    name: "Liberian Dollar",
    symbol: "$",
  },
},
{
  id: 113,
  name: "Guinea-Bissau",
  flag: "https://flagcdn.com/w160/gw.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Bissau",
  languages: ["Portuguese"],
  currency: {
    name: "West African CFA Franc",
    symbol: "CFA",
  },
},
{
  id: 114,
  name: "The Gambia",
  flag: "https://flagcdn.com/w160/gm.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Banjul",
  languages: ["English"],
  currency: {
    name: "Dalasi",
    symbol: "D",
  },
},
{
  id: 115,
  name: "Cape Verde",
  flag: "https://flagcdn.com/w160/cv.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Praia",
  languages: ["Portuguese"],
  currency: {
    name: "Cape Verdean Escudo",
    symbol: "$",
  },
},
{
  id: 116,
  name: "Ethiopia",
  flag: "https://flagcdn.com/w160/et.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Addis Ababa",
  languages: ["Amharic"],
  currency: {
    name: "Birr",
    symbol: "Br",
  },
},
{
  id: 117,
  name: "Kenya",
  flag: "https://flagcdn.com/w160/ke.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Nairobi",
  languages: ["English", "Swahili"],
  currency: {
    name: "Kenyan Shilling",
    symbol: "KSh",
  },
},
{
  id: 118,
  name: "Uganda",
  flag: "https://flagcdn.com/w160/ug.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Kampala",
  languages: ["English", "Swahili"],
  currency: {
    name: "Ugandan Shilling",
    symbol: "USh",
  },
},
{
  id: 119,
  name: "Tanzania",
  flag: "https://flagcdn.com/w160/tz.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Dodoma",
  languages: ["Swahili", "English"],
  currency: {
    name: "Tanzanian Shilling",
    symbol: "TSh",
  },
},
{
  id: 120,
  name: "Rwanda",
  flag: "https://flagcdn.com/w160/rw.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Kigali",
  languages: ["Kinyarwanda", "English", "French"],
  currency: {
    name: "Rwandan Franc",
    symbol: "RF",
  },
},
{
  id: 121,
  name: "Burundi",
  flag: "https://flagcdn.com/w160/bi.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Gitega",
  languages: ["Kirundi", "French", "English"],
  currency: {
    name: "Burundian Franc",
    symbol: "FBu",
  },
},
{
  id: 122,
  name: "Somalia",
  flag: "https://flagcdn.com/w160/so.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Mogadishu",
  languages: ["Somali", "Arabic"],
  currency: {
    name: "Somali Shilling",
    symbol: "Sh",
  },
},
{
  id: 123,
  name: "Djibouti",
  flag: "https://flagcdn.com/w160/dj.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Djibouti",
  languages: ["French", "Arabic"],
  currency: {
    name: "Djiboutian Franc",
    symbol: "Fdj",
  },
},
{
  id: 124,
  name: "Eritrea",
  flag: "https://flagcdn.com/w160/er.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Asmara",
  languages: ["Tigrinya", "Arabic", "English"],
  currency: {
    name: "Nakfa",
    symbol: "Nfk",
  },
},
{
  id: 125,
  name: "Sudan",
  flag: "https://flagcdn.com/w160/sd.png",
  region: "Africa",
  subregion: "Northern Africa",
  capital: "Khartoum",
  languages: ["Arabic", "English"],
  currency: {
    name: "Sudanese Pound",
    symbol: "SDG",
  },
},
{
  id: 126,
  name: "South Sudan",
  flag: "https://flagcdn.com/w160/ss.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Juba",
  languages: ["English"],
  currency: {
    name: "South Sudanese Pound",
    symbol: "£",
  },
},
{
  id: 127,
  name: "Egypt",
  flag: "https://flagcdn.com/w160/eg.png",
  region: "Africa",
  subregion: "Northern Africa",
  capital: "Cairo",
  languages: ["Arabic"],
  currency: {
    name: "Egyptian Pound",
    symbol: "E£",
  },
},
{
  id: 128,
  name: "Libya",
  flag: "https://flagcdn.com/w160/ly.png",
  region: "Africa",
  subregion: "Northern Africa",
  capital: "Tripoli",
  languages: ["Arabic"],
  currency: {
    name: "Libyan Dinar",
    symbol: "LD",
  },
},
{
  id: 129,
  name: "Tunisia",
  flag: "https://flagcdn.com/w160/tn.png",
  region: "Africa",
  subregion: "Northern Africa",
  capital: "Tunis",
  languages: ["Arabic"],
  currency: {
    name: "Tunisian Dinar",
    symbol: "DT",
  },
},
{
  id: 130,
  name: "Algeria",
  flag: "https://flagcdn.com/w160/dz.png",
  region: "Africa",
  subregion: "Northern Africa",
  capital: "Algiers",
  languages: ["Arabic", "Tamazight"],
  currency: {
    name: "Algerian Dinar",
    symbol: "دج",
  },
},
{
  id: 131,
  name: "Morocco",
  flag: "https://flagcdn.com/w160/ma.png",
  region: "Africa",
  subregion: "Northern Africa",
  capital: "Rabat",
  languages: ["Arabic", "Tamazight"],
  currency: {
    name: "Moroccan Dirham",
    symbol: "DH",
  },
},
{
  id: 132,
  name: "Mauritania",
  flag: "https://flagcdn.com/w160/mr.png",
  region: "Africa",
  subregion: "Western Africa",
  capital: "Nouakchott",
  languages: ["Arabic"],
  currency: {
    name: "Ouguiya",
    symbol: "UM",
  },
},
{
  id: 133,
  name: "Comoros",
  flag: "https://flagcdn.com/w160/km.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Moroni",
  languages: ["Comorian", "French", "Arabic"],
  currency: {
    name: "Comorian Franc",
    symbol: "CF",
  },
},
{
  id: 134,
  name: "Lesotho",
  flag: "https://flagcdn.com/w160/ls.png",
  region: "Africa",
  subregion: "Southern Africa",
  capital: "Maseru",
  languages: ["Sesotho", "English"],
  currency: {
    name: "Lesotho Loti",
    symbol: "L",
  },
},
{
  id: 135,
  name: "Eswatini",
  flag: "https://flagcdn.com/w160/sz.png",
  region: "Africa",
  subregion: "Southern Africa",
  capital: "Mbabane",
  languages: ["Swazi", "English"],
  currency: {
    name: "Lilangeni",
    symbol: "E",
  },
},
{
  id: 136,
  name: "Malawi",
  flag: "https://flagcdn.com/w160/mw.png",
  region: "Africa",
  subregion: "Eastern Africa",
  capital: "Lilongwe",
  languages: ["English", "Chichewa"],
  currency: {
    name: "Malawian Kwacha",
    symbol: "MK",
  },
},
{
  id: 137,
  name: "Costa Rica",
  flag: "https://flagcdn.com/w160/cr.png",
  region: "North America",
  subregion: "Central America",
  capital: "San José",
  languages: ["Spanish"],
  currency: {
    name: "Costa Rican Colón",
    symbol: "₡",
  },
},
{
  id: 138,
  name: "Luxembourg",
  flag: "https://flagcdn.com/w160/lu.png",
  region: "Europe",
  subregion: "Western Europe",
  capital: "Luxembourg",
  languages: ["Luxembourgish", "French", "German"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 139,
  name: "Liechtenstein",
  flag: "https://flagcdn.com/w160/li.png",
  region: "Europe",
  subregion: "Western Europe",
  capital: "Vaduz",
  languages: ["German"],
  currency: {
    name: "Swiss Franc",
    symbol: "CHF",
  },
},
{
  id: 140,
  name: "Monaco",
  flag: "https://flagcdn.com/w160/mc.png",
  region: "Europe",
  subregion: "Western Europe",
  capital: "Monaco",
  languages: ["French"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 141,
  name: "Andorra",
  flag: "https://flagcdn.com/w160/ad.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "Andorra la Vella",
  languages: ["Catalan"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 142,
  name: "Curaçao",
  flag: "/flags/cw.svg",
  region: "North America",
  subregion: "Caribbean",
  capital: "Willemstad",
  languages: ["Dutch", "Papiamento", "English"],
  currency: {
    name: "Netherlands Antillean guilder",
    symbol: "ƒ",
  },
},
{
  id: 143,
  name: "Vatican City",
  flag: "https://flagcdn.com/w160/va.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "Vatican City",
  languages: ["Italian", "Latin"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 144,
  name: "Malta",
  flag: "https://flagcdn.com/w160/mt.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "Valletta",
  languages: ["Maltese", "English"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 145,
  name: "Belarus",
  flag: "https://flagcdn.com/w160/by.png",
  region: "Europe",
  subregion: "Eastern Europe",
  capital: "Minsk",
  languages: ["Belarusian", "Russian"],
  currency: {
    name: "Belarusian Ruble",
    symbol: "Br",
  },
},
{
  id: 146,
  name: "Moldova",
  flag: "https://flagcdn.com/w160/md.png",
  region: "Europe",
  subregion: "Eastern Europe",
  capital: "Chișinău",
  languages: ["Romanian"],
  currency: {
    name: "Moldovan Leu",
    symbol: "L",
  },
},
{
  id: 147,
  name: "Estonia",
  flag: "https://flagcdn.com/w160/ee.png",
  region: "Europe",
  subregion: "Northern Europe",
  capital: "Tallinn",
  languages: ["Estonian"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 148,
  name: "Latvia",
  flag: "https://flagcdn.com/w160/lv.png",
  region: "Europe",
  subregion: "Northern Europe",
  capital: "Riga",
  languages: ["Latvian"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 149,
  name: "Lithuania",
  flag: "https://flagcdn.com/w160/lt.png",
  region: "Europe",
  subregion: "Northern Europe",
  capital: "Vilnius",
  languages: ["Lithuanian"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 150,
  name: "Cyprus",
  flag: "https://flagcdn.com/w160/cy.png",
  region: "Asia",
  subregion: "Western Asia",
  capital: "Nicosia",
  languages: ["Greek", "Turkish"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 151,
  name: "Fiji",
  flag: "https://flagcdn.com/w160/fj.png",
  region: "Oceania",
  subregion: "Melanesia",
  capital: "Suva",
  languages: ["English", "Fijian", "Hindi"],
  currency: {
    name: "Fijian Dollar",
    symbol: "$",
  },
},
{
  id: 152,
  name: "Papua New Guinea",
  flag: "https://flagcdn.com/w160/pg.png",
  region: "Oceania",
  subregion: "Melanesia",
  capital: "Port Moresby",
  languages: ["English", "Tok Pisin", "Hiri Motu"],
  currency: {
    name: "Kina",
    symbol: "K",
  },
},
{
  id: 153,
  name: "Solomon Islands",
  flag: "https://flagcdn.com/w160/sb.png",
  region: "Oceania",
  subregion: "Melanesia",
  capital: "Honiara",
  languages: ["English"],
  currency: {
    name: "Solomon Islands Dollar",
    symbol: "$",
  },
},
{
  id: 154,
  name: "Vanuatu",
  flag: "https://flagcdn.com/w160/vu.png",
  region: "Oceania",
  subregion: "Melanesia",
  capital: "Port Vila",
  languages: ["Bislama", "English", "French"],
  currency: {
    name: "Vatu",
    symbol: "Vt",
  },
},
{
  id: 155,
  name: "Samoa",
  flag: "https://flagcdn.com/w160/ws.png",
  region: "Oceania",
  subregion: "Polynesia",
  capital: "Apia",
  languages: ["Samoan", "English"],
  currency: {
    name: "Tālā",
    symbol: "T",
  },
},
{
  id: 156,
  name: "Tonga",
  flag: "https://flagcdn.com/w160/to.png",
  region: "Oceania",
  subregion: "Polynesia",
  capital: "Nukuʻalofa",
  languages: ["Tongan", "English"],
  currency: {
    name: "Paʻanga",
    symbol: "T$",
  },
},
{
  id: 157,
  name: "Kiribati",
  flag: "https://flagcdn.com/w160/ki.png",
  region: "Oceania",
  subregion: "Micronesia",
  capital: "South Tarawa",
  languages: ["English", "Gilbertese"],
  currency: {
    name: "Australian Dollar",
    symbol: "$",
  },
},
{
  id: 158,
  name: "Micronesia",
  flag: "https://flagcdn.com/w160/fm.png",
  region: "Oceania",
  subregion: "Micronesia",
  capital: "Palikir",
  languages: ["English"],
  currency: {
    name: "United States Dollar",
    symbol: "$",
  },
},
{
  id: 159,
  name: "Marshall Islands",
  flag: "https://flagcdn.com/w160/mh.png",
  region: "Oceania",
  subregion: "Micronesia",
  capital: "Majuro",
  languages: ["Marshallese", "English"],
  currency: {
    name: "United States Dollar",
    symbol: "$",
  },
},
{
  id: 160,
  name: "Palau",
  flag: "https://flagcdn.com/w160/pw.png",
  region: "Oceania",
  subregion: "Micronesia",
  capital: "Ngerulmud",
  languages: ["Palauan", "English"],
  currency: {
    name: "United States Dollar",
    symbol: "$",
  },
},
{
  id: 161,
  name: "Nauru",
  flag: "https://flagcdn.com/w160/nr.png",
  region: "Oceania",
  subregion: "Micronesia",
  capital: "Yaren",
  languages: ["Nauruan", "English"],
  currency: {
    name: "Australian Dollar",
    symbol: "$",
  },
},
{
  id: 162,
  name: "Tuvalu",
  flag: "https://flagcdn.com/w160/tv.png",
  region: "Oceania",
  subregion: "Polynesia",
  capital: "Funafuti",
  languages: ["Tuvaluan", "English"],
  currency: {
    name: "Australian Dollar",
    symbol: "$",
  },
},
{
  id: 163,
  name: "Cook Islands",
  flag: "https://flagcdn.com/w160/ck.png",
  region: "Oceania",
  subregion: "Polynesia",
  capital: "Avarua",
  languages: ["English", "Cook Islands Māori"],
  currency: {
    name: "New Zealand Dollar",
    symbol: "$",
  },
},
{
  id: 164,
  name: "Niue",
  flag: "https://flagcdn.com/w160/nu.png",
  region: "Oceania",
  subregion: "Polynesia",
  capital: "Alofi",
  languages: ["Niuean", "English"],
  currency: {
    name: "New Zealand Dollar",
    symbol: "$",
  },
},
{
  id: 165,
  name: "San Marino",
  flag: "https://flagcdn.com/w160/sm.png",
  region: "Europe",
  subregion: "Southern Europe",
  capital: "San Marino",
  languages: ["Italian"],
  currency: {
    name: "Euro",
    symbol: "€",
  },
},
{
  id: 166,
  name: "Cuba",
  flag: "https://flagcdn.com/w160/cu.png",
  region: "North America",
  subregion: "Caribbean",
  capital: "Havana",
  languages: ["Spanish"],
  currency: {
    name: "Cuban Peso",
    symbol: "$",
  },
},
{
  id: 167,
  name: "Jamaica",
  flag: "https://flagcdn.com/w160/jm.png",
  region: "North America",
  subregion: "Caribbean",
  capital: "Kingston",
  languages: ["English"],
  currency: {
    name: "Jamaican Dollar",
    symbol: "$",
  },
},
{
  id: 168,
  name: "Haiti",
  flag: "https://flagcdn.com/w160/ht.png",
  region: "North America",
  subregion: "Caribbean",
  capital: "Port-au-Prince",
  languages: ["French", "Haitian Creole"],
  currency: {
    name: "Gourde",
    symbol: "G",
  },
},
{
  id: 169,
  name: "Dominican Republic",
  flag: "https://flagcdn.com/w160/do.png",
  region: "North America",
  subregion: "Caribbean",
  capital: "Santo Domingo",
  languages: ["Spanish"],
  currency: {
    name: "Dominican Peso",
    symbol: "$",
  },
},
{
  id: 170,
  name: "Bahamas",
  flag: "https://flagcdn.com/w160/bs.png",
  region: "North America",
  subregion: "Caribbean",
  capital: "Nassau",
  languages: ["English"],
  currency: {
    name: "Bahamian Dollar",
    symbol: "$",
  },
},
{
  id: 171,
  name: "Barbados",
  flag: "https://flagcdn.com/w160/bb.png",
  region: "North America",
  subregion: "Caribbean",
  capital: "Bridgetown",
  languages: ["English"],
  currency: {
    name: "Barbadian Dollar",
    symbol: "$",
  },
},
{
  id: 172,
  name: "Trinidad and Tobago",
  flag: "https://flagcdn.com/w160/tt.png",
  region: "North America",
  subregion: "Caribbean",
  capital: "Port of Spain",
  languages: ["English"],
  currency: {
    name: "Trinidad and Tobago Dollar",
    symbol: "$",
  },
},
{
  id: 173,
  name: "Saint Lucia",
  flag: "https://flagcdn.com/w160/lc.png",
  region: "North America",
  subregion: "Caribbean",
  capital: "Castries",
  languages: ["English"],
  currency: {
    name: "East Caribbean Dollar",
    symbol: "$",
  },
},
{
  id: 174,
  name: "Saint Vincent and the Grenadines",
  flag: "https://flagcdn.com/w160/vc.png",
  region: "North America",
  subregion: "Caribbean",
  capital: "Kingstown",
  languages: ["English"],
  currency: {
    name: "East Caribbean Dollar",
    symbol: "$",
  },
},
{
  id: 175,
  name: "Grenada",
  flag: "https://flagcdn.com/w160/gd.png",
  region: "North America",
  subregion: "Caribbean",
  capital: "St. George's",
  languages: ["English"],
  currency: {
    name: "East Caribbean Dollar",
    symbol: "$",
  },
},
{
  id: 176,
  name: "Dominica",
  flag: "https://flagcdn.com/w160/dm.png",
  region: "North America",
  subregion: "Caribbean",
  capital: "Roseau",
  languages: ["English"],
  currency: {
    name: "East Caribbean Dollar",
    symbol: "$",
  },
},
{
  id: 177,
  name: "Antigua and Barbuda",
  flag: "https://flagcdn.com/w160/ag.png",
  region: "North America",
  subregion: "Caribbean",
  capital: "Saint John's",
  languages: ["English"],
  currency: {
    name: "East Caribbean Dollar",
    symbol: "$",
  },
},
{
  id: 178,
  name: "Saint Kitts and Nevis",
  flag: "https://flagcdn.com/w160/kn.png",
  region: "North America",
  subregion: "Caribbean",
  capital: "Basseterre",
  languages: ["English"],
  currency: {
    name: "East Caribbean Dollar",
    symbol: "$",
  },
},
{
  id: 179,
  name: "Belize",
  flag: "https://flagcdn.com/w160/bz.png",
  region: "North America",
  subregion: "Central America",
  capital: "Belmopan",
  languages: ["English"],
  currency: {
    name: "Belize Dollar",
    symbol: "$",
  },
},
{
  id: 180,
  name: "Guatemala",
  flag: "https://flagcdn.com/w160/gt.png",
  region: "North America",
  subregion: "Central America",
  capital: "Guatemala City",
  languages: ["Spanish"],
  currency: {
    name: "Quetzal",
    symbol: "Q",
  },
},
{
  id: 181,
  name: "Costa Rica",
  flag: "https://flagcdn.com/w160/cr.png",
  region: "North America",
  subregion: "Central America",
  capital: "San José",
  languages: ["Spanish"],
  currency: {
    name: "Costa Rican Colón",
    symbol: "₡",
  },
},
{
  id: 182,
  name: "El Salvador",
  flag: "https://flagcdn.com/w160/sv.png",
  region: "North America",
  subregion: "Central America",
  capital: "San Salvador",
  languages: ["Spanish"],
  currency: {
    name: "United States Dollar",
    symbol: "$",
  },
},
{
  id: 183,
  name: "Honduras",
  flag: "https://flagcdn.com/w160/hn.png",
  region: "North America",
  subregion: "Central America",
  capital: "Tegucigalpa",
  languages: ["Spanish"],
  currency: {
    name: "Lempira",
    symbol: "L",
  },
},
{
  id: 184,
  name: "Nicaragua",
  flag: "https://flagcdn.com/w160/ni.png",
  region: "North America",
  subregion: "Central America",
  capital: "Managua",
  languages: ["Spanish"],
  currency: {
    name: "Córdoba",
    symbol: "C$",
  },
},
{
  id: 185,
  name: "Panama",
  flag: "https://flagcdn.com/w160/pa.png",
  region: "North America",
  subregion: "Central America",
  capital: "Panama City",
  languages: ["Spanish"],
  currency: {
    name: "Balboa",
    symbol: "B/.",
  },
},
{
  id: 186,
  name: "Paraguay",
  flag: "https://flagcdn.com/w160/py.png",
  region: "South America",
  subregion: "South America",
  capital: "Asunción",
  languages: ["Spanish", "Guaraní"],
  currency: {
    name: "Guaraní",
    symbol: "₲",
  },
},
{
  id: 187,
  name: "Uruguay",
  flag: "https://flagcdn.com/w160/uy.png",
  region: "South America",
  subregion: "South America",
  capital: "Montevideo",
  languages: ["Spanish"],
  currency: {
    name: "Uruguayan Peso",
    symbol: "$",
  },
},
{
  id: 188,
  name: "Chile",
  flag: "https://flagcdn.com/w160/cl.png",
  region: "South America",
  subregion: "South America",
  capital: "Santiago",
  languages: ["Spanish"],
  currency: {
    name: "Chilean Peso",
    symbol: "$",
  },
},
{
  id: 189,
  name: "Bolivia",
  flag: "https://flagcdn.com/w160/bo.png",
  region: "South America",
  subregion: "South America",
  capital: "Sucre",
  languages: ["Spanish", "Quechua", "Aymara"],
  currency: {
    name: "Boliviano",
    symbol: "Bs",
  },
},
{
  id: 190,
  name: "Peru",
  flag: "https://flagcdn.com/w160/pe.png",
  region: "South America",
  subregion: "South America",
  capital: "Lima",
  languages: ["Spanish", "Quechua", "Aymara"],
  currency: {
    name: "Sol",
    symbol: "S/",
  },
},
{
  id: 191,
  name: "Ecuador",
  flag: "https://flagcdn.com/w160/ec.png",
  region: "South America",
  subregion: "South America",
  capital: "Quito",
  languages: ["Spanish"],
  currency: {
    name: "United States Dollar",
    symbol: "$",
  },
},
{
  id: 192,
  name: "Colombia",
  flag: "https://flagcdn.com/w160/co.png",
  region: "South America",
  subregion: "South America",
  capital: "Bogotá",
  languages: ["Spanish"],
  currency: {
    name: "Colombian Peso",
    symbol: "$",
  },
},
{
  id: 193,
  name: "Venezuela",
  flag: "https://flagcdn.com/w160/ve.png",
  region: "South America",
  subregion: "South America",
  capital: "Caracas",
  languages: ["Spanish"],
  currency: {
    name: "Bolívar",
    symbol: "Bs.",
  },
},
{
  id: 194,
  name: "Guyana",
  flag: "https://flagcdn.com/w160/gy.png",
  region: "South America",
  subregion: "South America",
  capital: "Georgetown",
  languages: ["English"],
  currency: {
    name: "Guyanese Dollar",
    symbol: "$",
  },
},
{
  id: 195,
  name: "Suriname",
  flag: "https://flagcdn.com/w160/sr.png",
  region: "South America",
  subregion: "South America",
  capital: "Paramaribo",
  languages: ["Dutch"],
  currency: {
    name: "Surinamese Dollar",
    symbol: "$",
  },
},
];